### ISSUE TITLE
Could we have a react JS example?

### ISSUE THREAD

**Issue by john012343210** [Azure-Samples/aoai-realtime-audio-sdk#10]
Could we have a react JS example?

**Comment by rdvo** [comment]
or can someone modify the openai react example to work with azure deployments? Please

**Comment by glecaros** [comment]
we are working on more samples, I'll try to prioritize one using react

**Comment by BryanChunkc** [comment]
Looking forward!

**Comment by fajri-droid** [comment]
🔥🔥🔥

**Comment by fajri-droid** [comment]
https://t.me/catizenbot/bombie?startapp=g_1002_1019009

**Comment by Ben-Pattinson** [comment]
Could we have the React front end with a .net API backend? I am finding it impossible to get the audio to play correctly. I get audio back, and it's super-slow and has interference., It's the right words just SSSSSSSLLLLLLLLLLLLLLOOOOOOOOWWWWWWWWWW and loads of interference. I presume there's some magic sauce I am missing in the processing or request, and consequently the returned audio does not match the playback expectations. However it's non-trivial to figure this out! I believe I am getting binary data back from the API, which is different to the JavaScipt version which seems to get Base64 encoded data back. 

I expect many people will be running a C# API with a javascript/React front end.

**Comment by glecaros** [comment]
Hey, #64 added a react sample. I'll close this issue for now, if anything comes up please open a new one :)

**Comment by glecaros** [comment]
@Ben-Pattinson I'm planning on having something like that (for all three languages as the library is meant for backend consumption), can you please open a new issue to track that?
