### ISSUE TITLE
Issue while doing python setup

### ISSUE THREAD

**Issue by Divyanshusir** [Azure-Samples/aoai-realtime-audio-sdk#11]
### Issue with Python Sample Setup

While setting up the Python sample from the `aoai-realtime-audio-sdk/python/samples/README.md`, I encountered an issue.

#### Problem

At line 30 of the README, the instructions mention downloading `rtclient` by running the following command:

```bash
pip install rtclient-0.4.0-py3-none-any.whl
```

However, when I run this command, I get the following error:

(env) divyanshusharma@Divyanshu-Sharma python % pip install rtclient-0.4.0-py3-none-any.whl
WARNING: Requirement 'rtclient-0.4.0-py3-none-any.whl' looks like a filename, but the file does not exist
Processing ./rtclient-0.4.0-py3-none-any.whl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/Users/divyanshusharma/Desktop/aoai-realtime-audio-sdk/python/rtclient-0.4.0-py3-none-any.whl'

#### NOTE:
It seems that the .whl file is missing from the repository or from my local setup. Is there any missing .whl file in the repo, or am I missing something in the setup process?

Please help!

**Comment by iMicknl** [comment]
This seems missing from the documentation indeed.
You will need `rtclient-0.4.0-py3-none-any.whl` (or a later version) which you can download here: https://github.com/Azure-Samples/aoai-realtime-audio-sdk/releases. 

Or you can leverage https://github.com/Azure-Samples/aoai-realtime-audio-sdk/blob/main/python/samples/download-wheel.sh or https://github.com/Azure-Samples/aoai-realtime-audio-sdk/blob/main/python/samples/download-wheel.ps1 to download the latest version.
