### ISSUE TITLE
download-pkg.sh in https://github.com/Azure-Samples/aoai-realtime-audio-sdk/tree/main/python/samples does not exist

### ISSUE THREAD

**Issue by SeryioGonzalez** [Azure-Samples/aoai-realtime-audio-sdk#31]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by glecaros** [comment]
Hi @SeryioGonzalez, thanks for reaching how. Can you please elaborate a bit on the problem you are seeing?

**Comment by glecaros** [comment]
hi @SeryioGonzalez, thanks for pointing that out, someone created a PR in parallel and fixed this. I'll close this but reach out if anything else comes up 😄
