### ISSUE TITLE
Python client_sample.py not working - only no vad is working

### ISSUE THREAD

**Issue by matthaeus-deutsch-parloa** [Azure-Samples/aoai-realtime-audio-sdk#35]
### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Follow all steps in the Readme and run the `client_sample.py` with any input.

### Any log messages given by the failure
It seems the input recognized is none:
```
[input_item=item_AH8qtozEODrqYcXqIaCoE] Previous Id: None
[input_item=item_AH8qtozEODrqYcXqIaCoE] Transcript: None
[input_item=item_AH8qtozEODrqYcXqIaCoE] Audio Start [ms]: 96
[input_item=item_AH8qtozEODrqYcXqIaCoE] Audio End [ms]: 800
```

### Expected/desired behavior

Yesterday the example was working fine, it seems its broken from today onwards.

### OS and Version?
macOS

### Versions
rt-client 0.4.4

### Mention any other details that might be useful
The issue is both with openai and azure. As said, 24 hours ago everything was running fine.

**Comment by glecaros** [comment]
Hi @matthaeus-deutsch-parloa, we just released a new package version (and updated the samples accordingly), can you please verify if you are still having trouble?

**Comment by matthaeus-deutsch-parloa** [comment]
Thanks @glecaros !

I get the following error after pulling and reinstalling 0.5.0 with both client_sample.py and client_sample_no_vad.py:

```
TypeError: RTLowLevelClient._get_azure_params() missing 1 required positional argument: 'self'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10b103800>
```

**Comment by glecaros** [comment]
hi @matthaeus-deutsch-parloa, I just fixed and generated a new release with the fix :) thanks for reporting this!

**Comment by matthaeus-deutsch-parloa** [comment]
Thanks @glecaros , its working again.
