### ISSUE TITLE
[python] `status` is not a field of `ResponseFunctionCallOutputItem`

### ISSUE THREAD

**Issue by yulin-li** [Azure-Samples/aoai-realtime-audio-sdk#55]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

In Python implementation, `ResponseFunctionCallOutputItem` contains a required field of `status`

https://github.com/Azure-Samples/aoai-realtime-audio-sdk/blob/87ca3d66a20dffac4b90ff1446f153504437ff08/python/rtclient/models.py#L365-L367

https://github.com/Azure-Samples/aoai-realtime-audio-sdk/blob/87ca3d66a20dffac4b90ff1446f153504437ff08/python/rtclient/models.py#L383-L386

While the openapi definition has no such field

https://github.com/Azure-Samples/aoai-realtime-audio-sdk/blob/87ca3d66a20dffac4b90ff1446f153504437ff08/realtime-openapi3.yml#L1078-L1083

**Comment by glecaros** [comment]
Fixing this same problem in js in this  PR #60, will close this once I generate new versions for both languages
