### ISSUE TITLE
Is it possible to let the copilot start the conversation automatically?

### ISSUE THREAD

**Issue by zmssp** [Azure-Samples/aoai-realtime-audio-sdk#63]
I want the copilot to start the conversation **automatically**, **do not wait for the user** to start the conversation.

I tried several prompts, like "Copilot, please start the conversation **automatically** and **greet the use** with welcome message",  "Copilot, please greet user actively, do not wait user to start the conversation".

However, the copilot **does not start the conversation automatically**, it still waits for the customer to start the conversation. 
 
**Is it possible to let the copilot start the conversation automatically?**
If yes, how to write the correct prompt.

**Comment by glecaros** [comment]
hi @zmssp, you can probably achieve this by automatically sending a text item (could be a message like "I have just joined the conversation, please introduce yourself and tell me what you can do.")
