### ISSUE TITLE
Missing package.json dependency

### ISSUE THREAD

**Issue by skyalbrigonia** [Azure-Samples/aoai-realtime-audio-sdk#8]
Hello!

Following the readme i was trying to run `npm install` but an error occurred:

`npm warn tarball tarball data for rt-client@file:/Users/andrea.albrigoni/aoai-realtime-audio-sdk/javascript/samples/rt-client-0.4.6.tgz (sha512-GaKPJ1wLHgw23dc+ekqPAdHycRKlX1kq9/NmzwAoOpRjDfHDNcV/HfYoobwyLmNmentWXs0iPVd72aUTmNHC2Q==) seems to be corrupted. Trying again.`

this file is missing:

`  "dependencies": {
    "@azure/identity": "^4.4.1",
    "rt-client": "file:../rt-client-0.4.6.tgz"
  }`

**Comment by glecaros** [comment]
hello @skyalbrigonia, did you try running the `javascript/samples/download-pkg.sh` file (or otherwise download the package from the github release manually) before running `npm install`?

Thanks for reaching out :)

**Comment by bptstmlgt** [comment]
> Hello!
> 
> Following the readme i was trying to run `npm install` but an error occurred:
> 
> `npm warn tarball tarball data for rt-client@file:/Users/andrea.albrigoni/aoai-realtime-audio-sdk/javascript/samples/rt-client-0.4.6.tgz (sha512-GaKPJ1wLHgw23dc+ekqPAdHycRKlX1kq9/NmzwAoOpRjDfHDNcV/HfYoobwyLmNmentWXs0iPVd72aUTmNHC2Q==) seems to be corrupted. Trying again.`
> 
> this file is missing:
> 
> ` "dependencies": { "@azure/identity": "^4.4.1", "rt-client": "file:../rt-client-0.4.6.tgz" }`

Did you have an error while running `download-pkg.sh`?
Like maybe jq not installed?

Everything's fine after installing jq on my side.

**Comment by glecaros** [comment]
@bptstmlgt, thanks for figuring that out... I'll add `jq` as a requirement for the bash scripts in the documentation.

**Comment by skyalbrigonia** [comment]
yeah thank you! now it works!
