### ISSUE TITLE
Insufficient Usage Info in python and js SDK

### ISSUE THREAD

**Issue by BetterAndBetterII** [Azure-Samples/aoai-realtime-audio-sdk#83]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

In python rtclient sdk, Usage model has no sufficient token usage info.

In [realtime-openapi3.yml](https://github.com/Azure-Samples/aoai-realtime-audio-sdk/blob/main/realtime-openapi3.yml), the usage definition is complete, however, in rtclient sdk Usage [/python/rtclient/models.py](https://github.com/Azure-Samples/aoai-realtime-audio-sdk/blob/main/python/rtclient/models.py), the input and output type is just number, which is not correct.

![image](https://github.com/user-attachments/assets/39554414-6961-4528-88f1-abac464ea88c)

![image](https://github.com/user-attachments/assets/5d302c5f-d5fe-4343-9602-6f3ebca60550)

### Any log messages given by the failure
>

### Expected/desired behavior
>

The Usage model gives all usage info.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

win11

### Versions
>

latest rtclient 0.5.2

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by glecaros** [comment]
Hi @BetterAndBetterII, we just merged your PR where you fixed this, so I'll go ahead and close this issue.
